### ISSUE TITLE
INSTALL script - No $CONFROOT

### ISSUE THREAD

**Issue by Jestre** [daveajones/cartulary#16]
I cloned the repo and tried to install it, but I noticed it failed when trying to cd to /aggrivate, so I downloaded the zip file to try instead, and diff'd the two install files.  Both have a line to `cd $CONFROOT/aggrivate` yet $CONFROOT does not appear to be set anywhere, so it fails.

I looked to see if that should be INSTALLDIR, but it looks like it actually wanted the current installer folder, so I simply set that variable and all worked as expected.

I did notice that the upgrade scripts set and use CONFROOT, so I'm not sure if it was just something wonky about my install [Ubuntu 16.04].

**Comment by daveajones** [comment]
Thanks.  Testing fix.

**Comment by Jestre** [comment]
Comment added to the commit.

**Comment by daveajones** [comment]
I see what you mean now.  Thanks for the code.  I put the shell variable at the top in case we need it for something else later.
