### ISSUE TITLE
Alternatives to S3

### ISSUE THREAD

**Issue by ajroach42** [daveajones/cartulary#17]
Hi, 

I have a VPS. I'm considering deploying this to that VPS. Is there a way I could use something other than S3 to get the same functionality?

**Comment by daveajones** [comment]
You can use whatever hosting provider you want for the server instance.  The S3 component is just for object storage.  The idea here is that your server can live anywhere and doesn't have to be visible to the outside world.  Everything the FC server generates goes to web-served block storage (S3) and that's where the public interacts with it.

It's cheaper, more secure and means even if a thousand people visit your blog all at once your server never has to deal with that traffic.

If you purely want an RSS reader then you don't need S3 at all.  If you want to have FC build your microblog and RSS feeds publicly then you'll have to use S3 or another provider that supports the S3 protocol.
