### ISSUE TITLE
Screenshots?

### ISSUE THREAD

**Issue by sbrl** [daveajones/cartulary#20]
Hey! I found you through Kickball/awesome-selfhosted.

I suggest that you add some screenshots to the readme. This will let people know what it looks like before trying it out for themselves :-)

**Comment by daveajones** [comment]
Sure, I can do that.  There are basic demo videos here also:  https://www.youtube.com/playlist?list=PL2a3Zvipy_miO78D57HWuxSOgO8tNNSVa

I have a lot of demo videos I've posted over the years that I need to put up that are not in that list also.
