### ISSUE TITLE
Install issue with Nodejs

### ISSUE THREAD

**Issue by asozzi** [daveajones/cartulary#21]
Hi,
I tried installing it on DigitalOcean as per video. But its now on Ubunutu 18.04
The first thing that shows up after the sudo ... INSTALL comand is:

> installing Apache, PHP and some modules
Followed by a big Deprecation warning about Node.js 4.x LTA Argon is no longer actively supported.

![image](https://user-images.githubusercontent.com/5819864/48559518-11998600-e8ec-11e8-8489-12f9f4326c00.png)

After that the Installation just skips over the rest it seems. Hope this can be fixed (for us semi literate users ;-)

**Comment by daveajones** [comment]
I haven't tested on Ubuntu 18 LTS yet.  Spin up a 16 LTS droplet instead and see if that works.  Testing on 18 is on my to-do list.  Let me know.

**Comment by daveajones** [comment]
I got another report of this happening on older Ubuntu releases as well. Let me dig in and see how to fix.

**Comment by daveajones** [comment]
Worked on this a bit yesterday. A lot of the php packages changed with Ubuntu 18. It’ll take some time to work out and test. Will target next release for support.

**Comment by asozzi** [comment]
Thanks for the update!
PS: It did spit out the error message under LTS 16, BUT it went through
with the installation.

Angelo

**Comment by daveajones** [comment]
This was fixed in v0.7.6
